### ISSUE TITLE
CAN Readings

### ISSUE THREAD

**Issue by martinsmuts** [blandman/HappyLeaf#3]
Hi,

First of all, I think what you have done with the UI looks awesome! Way more impressive than Leaf Spy. 

I want to know how you actually got to interpret the readings from the CAN messages onto the app? Please excuse my ignorance, but I can't see where in the code the interpretation takes place using the canmsgs codes from xls. that you have used. How did you do this?

I am working on a similar project for my university project. I want to get readings from the Leaf and send it to a server where I can use it for estimating final SoC using the initial SOC at the beginning of a trip. Also, taking into consideration if headlights are on, air conditioning, current speed etc. 

Kind regards
Martin

**Comment by AshMartian** [comment]
Hi, sorry for the delay. 

Codes sent to the OBD are defined here: https://github.com/blandman/HappyLeaf/blob/master/app/services/flow-manager.js

Then are parsed here: https://github.com/blandman/HappyLeaf/blob/master/app/services/data-manager.js

**Comment by martinsmuts** [comment]
Thanks so much for your reply. I really appreciate it.
