### ISSUE TITLE
Unable to get it running

### ISSUE THREAD

**Issue by apexad** [blandman/HappyLeaf#4]
I am currently using Leaf Spy on my iPhone with success.

However, I am unable to get HappyLeaf working.  I am running Mac OS High Sierra. I had node-js 9 already installed.  I installed bower with `brew install bower`.  I have also installed ember with `brew install ember`
I am sure it is something with my node or bower or ember setup.  I am following the steps to clone and then run `npm install` and `bower install`.

Running `ember serve` gives me the following error:

Dang! Looks like a Build Error.
ENOENT: no such file or directory, open '/Users/alexmartin/GitHub/HappyLeaf/tmp/source_map_concat-input_base_path-oUovlI4C.tmp/bower_components/jquery.ui.touch-punch/dist/jquery.ui.touch-punch.js'

**Comment by AshMartian** [comment]
Hello!

What model Leaf do you have?

Thank you for digging into this, I had lots of problems with getting Gridstack working with jquery 1.12, made commits to ember-gridstack to help but needed touch punch. I added touch-punch to bower.json, can you pull again and let me know if this works? Otherwise, we could try a newer version of ember-gridstack (1.20)

**Comment by apexad** [comment]
2017 Nissan Leaf S.

I got a new error with your update:

Build Error (Concat)

ENOENT: no such file or directory, open '/Users/alexmartin/GitHub/HappyLeaf/tmp/source_map_concat-input_base_path-mh8Z7ZXD.tmp/bower_components/gridstack/dist/gridstack.js'


Stack Trace and Error Report: /var/folders/8w/tnrcgt6x4k3dq2tz1k7w9xtr0000gn/T/error.dump.53e5beda56f139f6fa0af7706aeee0af.log

I made the following change to `bower.json`:

```diff
     "chartjs": "2.1.6",
     "jquery-ui": "^1.11.4",
     "lodash": "^4.13.1",
-    "gridstack.js": "https://github.com/troolee/gridstack.js.git",
+    "gridstack": "^0.3.0",
     "jquery.ui.touch": "*",
     "jquery.ui.touch-punch": "*",
     "components-font-awesome": "^4.7.0"
```

after running `bower install` again, it looks like I am up and running!

**Comment by AshMartian** [comment]
Awesome!

I also have a 2017 Leaf S, the version from the Google Play store and beta download link work with Bluetooth/Wifi.

I have not done extensive iOS testing, Wifi seemed pretty stable but BLE was always problematic. I am currently working on a custom Cordova module to replace the connection manager and flow manager, it will be able to connect to BLE/BT2/Wifi all in the same module and automatically query the car with given json config. I'll have more time in May to push a big update including this, we should see native performance.

**Comment by AshMartian** [comment]
Let me know if you have any success, I am very eager to know if you're able to use HappyLEAF.

**Comment by apexad** [comment]
I sent you a request for access to the iOS testfligh beta by the way.

It doesn't look like Mac OS X is able to connect with my current bluetooth obd sensor, but that is not the fault of HappyLeaf.
What device are you using to connect and use the browser platform?  Raspberry Pi? or are you only using an Android device?

**Comment by AshMartian** [comment]
I am only using Android device right now, when I was testing iOS I used a Wifi Adapter with MacOS since the simulator will not allow Bluetooth. Otherwise run on the device from xCode.
For some reason I don't get emails from the Testflight beta, when I started Testflight was via invite only, only after did they add public betas.

**Comment by apexad** [comment]
So, I did run it on iOS too. You’re right that it does not seem to stay connected (via Bluetooth). Next thing I will try is on a Raspberry Pi. If it works there that would be really great! I’d rather not buy an Android device.

**Comment by apexad** [comment]
Be sure to checkout my comment on https://github.com/blandman/HappyLeaf/commit/5848650401197c026cbfaa63b2f8ec9c53647419
Looks like you changed that incorrectly.
This compiles and runs on raspberry pi, but cannot load bluetooth devices in Chromium, what a shame.  Perhaps it may need to be `https`.

**Comment by AshMartian** [comment]
Woops, thank you. You would likely have to compile in Electron or a native Cordova wrapper to access Bluetooth.

**Comment by apexad** [comment]
I still think it's wrong. I think you want just `gridstack`, not `gridstack.js`

**Comment by AshMartian** [comment]
Gotcha, in the past I had problems with using gridstack and not gridstack.js, awesome if it's working for you. I'll do more testing and update.
